### PR TITLE
Obtain EUI-64 from mbed HAL

### LINKED ISSUE #17: EUI64 is not constant when using MCR20 radio
When using Thread configuration and MCR20 radio the method "device_eui64_get" returns slightly different EUI64 every time when the device is restarted. 

This error is a copy of https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/202. The issue is copied here as this is appropriate place for the correction.

### PR DESCRIPTION
**Pull request by kjbracey-arm**
The MCR20A does not have any built-in EUI-64, but this driver was
attempting to read the initial state of the address registers to get
one.

The address registers are initialised to ff:ff:ff:ff:ff:ff:ff:ff on
reset, but the read routine was broken - it read direct registers 7-14
when it should have read indirect registers 7-14. This meant it read a
slightly-random bitstring, as direct registers 12-14 are part of a
timer.

Modify the driver to get a 48-bit MAC address from `mbed_mac_address`
and convert that to a EUI-64 for use with radio.

Fixes #17.

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
Good question. A semi-stable something but seems to vary in one or more bits after each reset - follow a few links above to this: https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/199#issuecomment-402891001

And the base value seems to be somewhat different between boards, but I think it is just uninitialised registers, rather than any attempt to actually be an EUI-64. No information I can find anywhere only suggests the device has an EUI-64 built-in.

What still bothers me is that the datasheet says those registers should be initialised to all-1s. Suggests something still not understood.

**Comment by SeppoTakalo** [comment]
Hmm.. "Reset value: FFh"

Semi-random looks like actually transmission error...

**Comment by SeppoTakalo** [comment]
Reference: https://www.nxp.com/docs/en/reference-manual/MCR20RM.pdf

**Comment by kjbracey-arm** [comment]
I did originally assume it was transmission error, particularly as these registers are read before full power-on. (Legal, but may have different timing requirements).

But:
* Moving the reads to after full power-on doesn't change behaviour
* There's no evidence of any other SPI transmission problems
* I've just confirmed the values only change on reset, *not* successive reads

And then there's no documentary evidence that we should expect to read back a EUI from there on reset - only reason to suppose we should is that that's the way the code is written. 

Weird/unfortunate that you don't get the documented all-ones though. Mistake would have been spotted sooner.

**Comment by kjbracey-arm** [comment]
Actually, scrub part of that, my successive-read test was flawed. Redid it and I just got this, which is bizarre:

```
HW EUI-64: 00:06:23:62:2b:03:f0:09
HW EUI-64: 00:07:3e:62:2b:03:f0:09
HW EUI-64: 00:08:58:62:2b:03:f0:09
HW EUI-64: 00:09:73:62:2b:03:f0:09
HW EUI-64: 00:0a:8d:62:2b:03:f0:09
HW EUI-64: 00:0b:a8:62:2b:03:f0:09
HW EUI-64: 00:0c:c3:62:2b:03:f0:09
HW EUI-64: 00:0d:dd:62:2b:03:f0:09
HW EUI-64: 00:0e:f8:62:2b:03:f0:09
HW EUI-64: 00:10:13:62:2b:03:f0:09
```
Okay, let's dig a bit further here. Too much unexplained.

**Comment by kjbracey-arm** [comment]
There's a mistake in the "read" routine - it's reading *direct* registers 7-14. It should be reading *indirect* registers 7-14.

So the driver as it stands is reading a bunch of registers which includes a timer, and programming that into the MAC address registers (as the write routine is correct).

Once corrected, we read back `ff:ff:ff:ff:ff:ff:ff:ff:ff` as advertised.

**Comment by kjbracey-arm** [comment]
Updated commit message with fuller explanation.

**Comment by kjbracey-arm** [comment]
One issue to note here is that not that many boards actually do have a built-in `mbed_mac_address` - the K64F does, but not many others. If using this radio on a board without its own MAC address, the application would need to provide an implementation.

**Pull request merged**
